# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "firewire_ohci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2a7e95ed-02e6-4f63-b14a-bc9a23d5c790";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/720e46a1-fdd1-407b-a158-b3cbb8fa5aa6"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
